### ISSUE TITLE
Running the test-node full example

### ISSUE THREAD

**Issue by eselkin** [input-output-hk/plutus-apps#148] opened 2021-11-25 21:51 UTC
## Summary
Completing steps in: `$PLUTUS/plutus-pab/test-node/README.md`

Step 3 works and starts the node and appears to sync with the testnet.
Step 4 appears to have problems. While the service is listening on port 8090, it makes no connection.

## Steps to reproduce

1. Go to ''.../plutus-apps/plutus-pab/test-node/README.md"
2. Run step 1 (downloaded linux version of cardano-node - installed in /usr/local/bin/cardano-node and added to PATH)
3. Run step 2 build completes (with addition of plutus-doc -- see PR #147)
4. Run step 3 (starts node and appears to function... takes a while to sync then shows: 
    ```
    [eli-DSK:cardano.node.ChainDB:Notice:33] [2021-11-25 21:40:36.38 UTC] Chain extended, new tip: b4354a56ce5880e2fbac02972d3b5eeaf99a0a7f3a0c1ed42a0eb1cf0141ac2a at slot 43507220
    ```
5. Run step 4 (starts but never connects):
    ```
    [cardano-wallet.network:Warning:61] [2021-11-25 21:36:33.51 UTC] {"string":"Couldn't connect to node (x748). Retrying in a bit..."}
    [cardano-wallet.network:Warning:14] [2021-11-25 21:36:33.51 UTC] {"string":"Couldn't connect to node (x756). Retrying in a bit..."}
    [cardano-wallet.pools-engine:Warning:27] [2021-11-25 21:36:34.24 UTC] {"string":"Still not syncing. Applied 0 blocks, 0 rollbacks in the last 30.000935632s. Currently at slot 0. (not applying blocks)"}
    [cardano-wallet.ntp-client:Notice:852] [2021-11-25 21:36:36.31 UTC] {"string":"ntp client experienced error     Network.Socket.ByteString.sendManyTo: does not exist (Network is unreachable) when sending packet"}
    [cardano-wallet.ntp-client:Notice:854] [2021-11-25 21:36:37.41 UTC] {"string":"ntp client experienced timeout using IPv6 protocol"}
    [cardano-wallet.ntp-client:Notice:853] [2021-11-25 21:36:37.91 UTC] {"string":"ntp client experienced timeout using IPv4 protocol"}
    ```` 
6. Run step 5 (cabal exec -- cardano-wallet recovery-phrase generate runs and generates phrase... added to json as displayed from cat in this step... should make docs a little clearer here).
7. Attempt to load wallet (curl just hangs)

## Expected behavior
Expect Step 4 to not show repeated unreachable errors and step 5 for POST to respond.

## System info (please complete the following information):

- OS: Ubuntu
- Version: 20.04
- hash for plutus-apps:`a78e858f77cd3ecb76877351e0832ee5643f09a9`

## Screenshots and attachments
Covered in text above.

## Additional context
N/A

**Comment by bhoudebert** [comment] 2021-11-29 07:52
Are you sure:
- everything is synced (node, wallet, chain index)
- there should be no hanging even unsynced from my experience because unsynced is a normal state

You should be able to know if they are synced by asking servers endpoint  (for chain compare slot, I think I saw a PR talking about a percentage also - took hours to me to sync). 

For example for the node you could use the cli like this
```shell
export CARDANO_NODE_SOCKET_PATH= ... path to node socket ...
client/cardano-cli query tip --testnet-magic 1097911063
```

You have also the wallet endpoint available
```shell
curl --location --request GET 'http://localhost:8090/v2/network/information'
```

From what I remember, even if not all is sync creating a wallet is instant too. Point is you will have to wait `sync` to be able to ask faucet some funds

**Comment by eselkin** [comment] 2021-11-29 23:24
Actually, I forgot to update. In order to actually get the sync to work for the complete test-node I had to create the node.sock socket in ...testnet/node.sock. It doesn't get created otherwise. This is not a normal thing.

**Comment by bhoudebert** [comment] 2021-11-29 23:29
I do not understand, you should not create manually the socket file it should be done by the server.

Do you have folder permission issue ?

**Comment by eselkin** [comment] 2021-11-29 23:30
Nope, no permissions problem. Same user is creating it manually as would create it with the server.

**Comment by bhoudebert** [comment] 2021-11-29 23:34
Really weird situation (never saw such thing) and if you create it manually does the chain doing Sync from node ? If not node is certainly not using it or even started (?)

**Comment by eselkin** [comment] 2021-11-29 23:35
Yes

**Comment by ak3n** [comment] 2021-12-02 12:21
Thanks for the issue!

It's hard to say anything as it seems the problem is with the wallet (local network settings maybe?). I don't see anything related to PAB. Maybe worth opening an issue there https://github.com/input-output-hk/cardano-wallet.

**Comment by ak3n** [comment] 2021-12-16 12:48
I'm closing this one as the problem seems to be not on our side but feel free to reopen.

Also we bumped the cardano-wallet's version. It might help.

**Closed by ak3n** 2021-12-16 12:48 UTC
Labels: bug
