### ISSUE TITLE
PAB simulation hangs after first transaction

### ISSUE THREAD

**Issue by stanislav-az** [input-output-hk/plutus-apps#352] opened 2022-03-09 13:06 UTC
### Summary

I'm not able to start `Plutus.PAB.Simulator` after updating to latest `plutus-apps` commit. It hangs after printing log for the first transaction:
```
[INFO] W[1]: Balancing an unbalanced transaction:
               Tx:
                 Tx da143e3b8aa55c7793ec29a717c66620e96d841c011d1a4bef26a5063216ef5c:
                   {inputs:
                   collateral inputs:
                   outputs:
                     - Value (Map [(,Map [("",2000000)])]) addressed to
                       PubKeyCredential: a2c20c77887ace1cd986193e4e75babd8993cfd56995cd5cfce609c2 (no staking credential)
                   mint: Value (Map [])
                   fee: Value (Map [])
                   mps:
                   signatures:
                   validity range: Interval {ivFrom = LowerBound NegInf True, ivTo = UpperBound PosInf True}
                   data:}
               Requires signatures:
               Utxo index:
               Validity range:
                 (-pab-simulation: <stdout>: commitAndReleaseBuffer: invalid argument (invalid character)
```

### Steps to reproduce the behavior

1. checkout main branch of `plutus-apps`
2. enter `nix-shell`
3. run any simulation e.g. `cabal run plutus-pab-test-full`

### Actual Result

Logs stop during balancing first tx: 
```
    Executing contracts.
      Guessing Game:                                   [INFO] Slot 0: TxnValidate 8cc29ae699b906e31bbb8b3e55eea772477cd9aeb7154ce8526752f6f986a31a
[INFO] Initialising contract GameStateMachine with ID 9c96a15c-647a-41f6-ad60-2b60a7069181
[INFO] Activated instance 9c96a15c-647a-41f6-ad60-2b60a7069181 on W[1]
[INFO] W[1]: Balancing an unbalanced transaction:
               Tx:
                 Tx db0e7302d24828592996f42ff9f0672b0e7a3c630c9f9b34795e0411dfd63727:
                   {inputs:
                   collateral inputs:
                   outputs:
                     - Value (Map [(,Map [("",15000000)])]) addressed to
                       ScriptCredential: 1bf560abcbb2517692fa58b726497293fb33bda17cac62b27a19e9e3 (no staking credential)
                   mint: Value (Map [])
                   fee: Value (Map [])
                   mps:
                   signatures:
                   validity range: Interval {ivFrom = LowerBound NegInf True, ivTo = UpperBound PosInf True}
                   data:
                     <")\232\241o\218\SI\162\242\254\236`ca\200|b\145(\CAN\241\236f\STX\185*\194\238\224",
                     "guess",
                     "^\136H\152\218(\EOTqQ\208\229o\141\198)'s`=\rj\171\189\214*\DC1\239r\GS\NAKB\216">}
               Requires signatures:
               Utxo index:
                 ( 8cc29ae699b906e31bbb8b3e55eea772477cd9aeb7154ce8526752f6f986a31a!5
                 , - Value (Map [(,Map [("",100000000000)])]) addressed to
                     PubKeyCredential: a2c20c77887ace1cd986193e4e75babd8993cfd56995cd5cfce609c2 (no staking credential) )
               Validity range:
                 (-plutus-pab-test-full: <stdout>: commitAndReleaseBuffer: invalid argument (invalid character)
```

### Expected Result

Logs continue to validate first transaction.

### Describe the approach you would take to fix this

Probably the error is related to transaction validity range

### System info

Ubuntu 20.04
plutus-apps@ 255879bb998fe1329abab3e07698f834e6cbbba6
same result@ c4960ae14b187978bf41832313370d282f648eee

**Comment by kk-hainq** [comment] 2022-03-10 06:32
I cannot reproduce this with `cabal run plutus-pab-test-full` inside the Nix shell neither in the listed commits nor HEAD. Have you tried running it after a `cabal clean`?

**Comment by stanislav-az** [comment] 2022-03-10 06:53
Yes, I've tried `cabal clean`. But I probably do need to remove whole `~/.cabal` also.

**Comment by olgaklimenko** [comment] 2022-04-19 10:29
Following steps helped me:

1) Install `glibcLocales` package:
`nix-env -iA nixpkgs.glibcLocales`

2) Add to ~/.profile:
`export LOCALE_ARCHIVE="$(nix-env --installed --no-name --out-path --query glibc-locales)/lib/locale/locale-archive"`

**Comment by koslambrou** [comment] 2022-05-22 21:46
Closing. Reopen if the problem persists.

**Closed by koslambrou** 2022-05-22 21:46 UTC
Labels: bug
