### ISSUE TITLE
Request for dApp deployment documentation/how-to's

### ISSUE THREAD

**Issue by mikekeke** [input-output-hk/plutus-apps#59] opened 2021-10-27 14:17 UTC
## Area

[] *Plutus Foundation* Related to the GHC plugin, Haskell-to-Plutus compiler, on-chain code
[x] *Plutus Application Framework* Related to the Plutus application backend (PAB), emulator, Plutus libraries
[] *Marlowe* Related to Marlowe
[] *Other* Any other topic (Playgrounds, etc.)

## Describe the feature you'd like
While working on deployment story it feels like explicit description of workflow of how to go from `On-chain + Off-chain code` to `dApp` is missing.

It looks like for dApp beind deployed developer need:

1. Hook `Contract` endpoints to PAB handlers and build PAB executable with `Contract(s)` embedded in it.
2. Run PAB executable pointing it to the desired chain index, Node socket and network id.
3. Provide a way for `user wallets` to balance and sign partial transactions, built by `Off-chain code` of `dApp`

Some  parts of the workflow doesn't look quite clear considering the following:

- [ ] For providing REST API for `Contract` several examples available now:
  - `Simulator` related from [pioneer lectures](https://plutus-pioneer-program.readthedocs.io/en/latest/pioneer/week6.html#oracle-pab) - seems to be outdated
  - Another `Simulator` related for [uniswap](https://github.com/input-output-hk/plutus/blob/plutus-pab/v0.0.2/plutus-pab/examples/uniswap/Main.hs#L42)
  - Via `runWith` from `Plutus.PAB.Run` - [link](https://github.com/input-output-hk/plutus/blob/plutus-pab/v0.0.2/plutus-pab/examples/Main.hs#L13)
 
  What is the recommended way to start "production" version of PAB for `Contract`?
(It looks like last one is a way to go, as [PAB demo](https://github.com/input-output-hk/plutus/tree/master/plutus-pab#running) uses it)
 
- [ ] PAB configuring: how to start PAB with ability to:
  - [ ] Set network to connect to
  - [ ] Set node socket
  - [ ] Set chain index to use for querying
 
  Note: a way to start chain index for testnet (Alonzo testnet as example):
 
  ```
  cabal run exe:plutus-chain-index -- --socket-path /path/  to/node.socket --db-path /path/to/chain-index.db --network-id 8 start-index
  ```
 
- [ ] PAB - WBE integration.
 
  [WBE docs says](https://github.com/input-output-hk/cardano-wallet/wiki/Using-Cardano-Wallet-with-Plutus-Application-Backend#balance-transaction) that:
 
  ```
  Plutus Application Backend provides payload of unbalanced transaction
  ```
 
  [Hosted deployment scenario says](https://plutus.readthedocs.io/en/latest/plutus/explanations/pab.html#hosted) that:
 
  ```
  The PAB produces a link (URI) for each partial transaction that needs to be balanced and signed. When the user clicks the link, the user’s operating system opens the wallet that is registered to handle the link schema
  ```
 
Does this mean, that `dApp` developer's task will be to deliver link for partial transaction to user through `dApp`'s frontend, and then user will click it and whatever wallet registered for that (and if it works through WBE) will execute REST API call with CBOR-encoded transaction in request body as [Using Cardano Wallet with Plutus Application Backend](https://github.com/input-output-hk/cardano-wallet/wiki/Using-Cardano-Wallet-with-Plutus-Application-Backend) describes it?
  Who then submits transaction after it's balanced and signed - `PAB` or `Wallet`? If `PAB`, how does it get signed and balanced transaction back from the user?

## Describe alternatives you've considered

Cover topics above in some How-to documentation section.

## Additional context / screenshots

-

**Comment by bhoudebert** [comment] 2021-11-10 13:40
It was not very clear to me, how signing/security will happen, until I read your issue, so thank you.

From testing/emulator we never saw anything about a smart contract endpoint producing an output as link but it really seems to be a right answer for security which is similar to my wondering [issue about signing](https://github.com/input-output-hk/plutus-apps/issues/90) too.

But then It starts to be confusing because our current (from tutorials to examples) pab smart contract are using functions like `submitTx` and even some `awaitTxConfirmed` and they obviously not saying anything about any external signing flow (which is great for testing so)

Does that mean that these functions should not be used for real code? Are we able currently to generate such kind of links?

**Comment by bhoudebert** [comment] 2021-11-10 14:03
I have also found this https://github.com/input-output-hk/plutus/blob/master/notes/smart-contract-backend/scb.md which should cover the expected process.

**Comment by bhoudebert** [comment] 2021-11-10 18:21
ok google was my friend this time:

https://input-output-hk.github.io/cardano-wallet/user-guide/common-use-cases/pab

**Comment by mikekeke** [comment] 2021-11-11 12:14
@bhoudebert  Here is some more details on PAB: https://plutus-apps.readthedocs.io/en/latest/plutus/explanations/pab.html

**Comment by bhoudebert** [comment] 2021-11-11 17:09
Thxs I already read this =)

I just found that we have to run the PAB with `runWith` (found it in plutus-app instead of starter) instead of Simulator.

For now calling a PAB endpoint is sending an unbalanced tx to the cardano-wallet which I assume triggers something like ask the client to sign it. Unfortunately I am not far away from this point as the mock wallet even if running does not seem to respond to the api (wallet is running but no api seems to respond, even pab fails trying to reach it).

I might have to test with a full env with a testnet wallet.

**Comment by mikekeke** [comment] 2021-11-15 08:00
@bhoudebert 
Maybe this will be useful: https://gist.github.com/mikekeke/883d56c38e0237444ac98ae5257e174f
This is 1st iteration of our "how-to"

**Comment by bhoudebert** [comment] 2021-11-15 08:15
@mikekeke I will have a look thanks, I did use also some docker for several parts (mostly wallet+node) but I think had issue again with some wallet validation.

I also saw something like `signingProcessConfig` did you achieve by chance to trigger this kind of process?

**Comment by mikekeke** [comment] 2021-11-15 08:22
@bhoudebert , also readme here has some instructions: https://github.com/input-output-hk/plutus-apps/tree/main/plutus-pab/test-node

>I also saw something like signingProcessConfig did you achieve by chance to trigger this kind of process?
I'm not quiet sure yet what is it atm. For our tests we used cardano-wallet integration and transaction signing was performed by cardano-wallet.

**Comment by bhoudebert** [comment] 2021-11-15 08:26
@mikekeke yes I used also this part but I remember that we using the local cluster the wallet was not aligned v2 api was missing.

That's why I was trying to run it also from sources. The docker-compose from cardano-wallet is a good start for that (just miss the chain index in it) letting us run our pab from sources.

**Comment by bhoudebert** [comment] 2021-11-15 09:48
Okay it seems normal ```Added: POST /wallets/{walletId}/transactions-balance (warning under development, may not behave as expected)``` it is not yet ready.

**Comment by alexandru-calinoiu** [comment] 2021-11-22 20:11
I think this PR https://github.com/input-output-hk/plutus-apps/pull/119 should solve one part of the problem, unfortunately don't see yet in it any updates to the samples or readme.

**Comment by bhoudebert** [comment] 2021-11-22 20:15
Yeah I just saw that too, they are starting it!

**Comment by silky** [comment] 2021-11-23 09:14
Hey all; I'm going to close this issue as it's a little bit unwieldy; but please do feel free to open more specific tickets so that we can address them :)

Thanks!

**Closed by silky** 2021-11-23 09:14 UTC
Labels: enhancement
